# Copyright (c) 2013, The Linux Foundation. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
#
#

# OCF specifc NSS cfi Makefile

NSS_CFI_MOD_NAME=qca-nss-cfi-ocf

obj-m += $(NSS_CFI_MOD_NAME).o
$(NSS_CFI_MOD_NAME)-objs = nss_cfi_ocf.o

obj ?= .

ccflags-y += -I$(obj)/../../ocf
ccflags-y += -I$(obj)/../../nss-crypto/include
ccflags-y += -I$(obj)/../include
ccflags-y += -I$(obj)/
