#!/bin/sh

[ -f /tmp/logfile ] || exit 0

r_version=$(cat /tmp/logfile | grep "version" | awk -F" " '{print $3}' | echo $(awk '{print $0}') | awk 'BEGIN{FS="."}{print $3}' | awk 'BEGIN{FS=")"}{print $1}')
n_version=$(cat /tmp/firmware_version | awk 'BEGIN{FS="."}{print $3}' | awk 'BEGIN{FS=")"}{print $1}')

rootfs_version=$(($r_version + 0))
firmware_version=$(($n_version + 0))

result=$(($rootfs_version - $firmware_version))

echo '' >> /tmp/logfile

if [ $result -lt 0 ]; then
	echo 'old' >> /tmp/logfile
fi

echo 'Upgrade check success2' >> /tmp/logfile

#echo "  rootfs version = $rootfs_version" > /dev/console
#echo "firmware version = $firmware_version" > /dev/console
