#!/bin/sh  /etc/rc.common
#
# Copyright (c) 2014 The Linux Foundation. All rights reserved.
#
# The shebang above has an extra space intentially to avoid having
# openwrt build scripts automatically enable this package starting
# at boot.

START=70

CONF_FILE=/etc/sysctl.d/qca-nss-ecm.conf

load_ecm() {
	[ -d /sys/module/ecm ] || insmod ecm

	sysctl -w net.bridge.bridge-nf-call-ip6tables=1
	sysctl -w net.bridge.bridge-nf-call-iptables=1
}

unload_ecm() {
	[ -d /sys/module/ecm ] && rmmod ecm

	sysctl -w net.bridge.bridge-nf-call-ip6tables=0
	sysctl -w net.bridge.bridge-nf-call-iptables=0
}

setopt() {
	local name=$1
	local val=$2

	grep -q "^${name}" ${CONF_FILE} && \
		sed -i "s,^${name}.*,${name}=${val}," ${CONF_FILE} || \
		echo "${name}=${val}" >> ${CONF_FILE}
}

delopt() {
	local name=$1

	sed -i "/^${name}/d" ${CONF_FILE}
}

restart() {
	proto=$(uci get network.wan.proto)
        log=$(sysctl -a | grep "net.bridge.bridge-nf-call-iptables")
        if [ "$proto" == "pptp" ]; then
                if [ "$log" == "net.bridge.bridge-nf-call-iptables = 1" ];then
                        /etc/init.d/qca-nss-ecm stop
                fi
        else
                if [ "$log" == "net.bridge.bridge-nf-call-iptables = 0" ];then
                        /etc/init.d/qca-nss-ecm start
                fi
		##check mode,if AP will sleep 10
		local sys_mode=$(get_sys_mode)
		[ "$sys_mode" == "2" ] && sleep 10

		echo 1 > /sys/devices/system/ecm_db/ecm_db0/defunct_all
	fi

	##check mode,if AP, The NSS is disabled.
	[ -e /etc/init.d/qca-nss-ecm ] && {
		local sys_mode=$(uci get system.main.system_mode)
		[ "$sys_mode" == "2" -o "$sys_mode" == "3" ] && /etc/init.d/qca-nss-ecm stop
	}
}

start() {
	proto=$(uci get network.wan.proto)
	log=$(sysctl -a | grep "net.bridge.bridge-nf-call-iptables")
	if [ "$proto" == "pptp" ]; then
		if [ "$log" == "net.bridge.bridge-nf-call-iptables = 1" ];then
			/etc/init.d/qca-nss-ecm stop
		fi
	else
		load_ecm

		setopt dev.nss.general.redirect 1
		setopt net.bridge.bridge-nf-call-ip6tables 1
		setopt net.bridge.bridge-nf-call-iptables 1
	fi

	countrycode=$(fw_printenv countrycode | awk -F"=" '{print $2}' | tr [a-f] [A-F])
	if [ "$countrycode" == "E1" ]; then
		echo "Reduce Power Loss for ERP requesting."
	else
		echo "0" > /proc/sys/dev/nss/clock/auto_scale
		echo "733000000" > /proc/sys/dev/nss/clock/current_freq
	fi

	##check mode,if AP, The NSS is disabled.
	[ -e /etc/init.d/qca-nss-ecm ] && {
		local sys_mode=$(uci get system.main.system_mode)
		[ "$sys_mode" == "2" -o "$sys_mode" == "3" ] && /etc/init.d/qca-nss-ecm stop
	}
}

stop() {
	unload_ecm

	delopt dev.nss.general.redirect
	delopt net.bridge.bridge-nf-call-ip6tables
	delopt net.bridge.bridge-nf-call-iptables
}
