#!/usr/bin/lua

--[[
    Copyright (c) 2013, AllSeen Alliance. All rights reserved.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
]]

local sys = require "luci.sys"
local json = require "luci.json"
local io = require "io"
local uci = require("luci.model.uci").cursor()
local wdev = "radio0"

uci:foreach("wireless", "wifi-device", function(s)
	if s["type"] == "mac80211" then
		wdev = s[".name"]
	end
end)

local has_iwinfo = pcall(require, "iwinfo")
if has_iwinfo then
	local iw = sys.wifi.getiwinfo(wdev)
	if iw then
		function scanlist(times)
			local i, k, v, m
			local l = { }

			function is_scan_entry_duplicate(a, b)
				return (a.bssid == b.bssid)
			end

			for i = 1, times do
				for k, v in ipairs(iw.scanlist) do
					local duplicate = false
					for _, m in ipairs(l) do
						if is_scan_entry_duplicate(m, v) then
							-- found duplicate entry, do not add it
							duplicate = true
							break
						end
					end
					if not duplicate then
						l[#l + 1] = v
					end
				end
			end

			table.sort(l, function(a, b) return (tonumber(a.signal) or 999) > (tonumber(b.signal) or 999) end )

			return l
		end

		local iw_scan_list = scanlist(5)
		local fout = io.open("/tmp/wifi_scan_results", "w")
		fout:write(luci.json.encode(iw_scan_list))
		fout:close()
	end
end
